[package]
name = "delta_lake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deltalake = { version = "0.16.5", features = ["datafusion", "s3"] }
tempdir = "0.3.7"
tokio = "1.35.1"
